create schema NORTHWIND

create table NORTHWIND.CATEGORIES(
CATEGORY_NAME VARCHAR (15),
DESCRIPTION VARCHAR (2000),
PICTURE VARCHAR (255))

create table NORTHWIND.CUSTOMERS(
CITY VARCHAR (15),
COMPANY_NAME VARCHAR (40),
CONTACT_NAME VARCHAR (30),
CONTACT_TITLE VARCHAR (30),
COUNTRY VARCHAR (15),
CUSTOMER_CODE VARCHAR (5),
CUSTOMER_ID NUMERIC (22),
FAX VARCHAR (24),
PHONE VARCHAR (24),
POSTAL_CODE VARCHAR (10),
REGION VARCHAR (15))

create table NORTHWIND.EMPLOYEES(
BIRTHDATE DATE,
CITY VARCHAR (15),
COUNTRY VARCHAR (15),
EMPLOYEE_ID NUMERIC (22),
EXTENSION VARCHAR (4),
FIRSTNAME VARCHAR (10),
HIREDATE DATE,
HOME_PHONE VARCHAR (24),
LASTNAME VARCHAR (20),
NOTES VARCHAR (2000),
PHOTO VARCHAR (255),
POSTAL_CODE VARCHAR (10),
REGION VARCHAR (15),
REPORTS_TO NUMERIC (22),
TITLE VARCHAR (30),
TITLE_OF_COURTESY VARCHAR (25))

create table NORTHWIND.ORDER_DETAILS(
ORDER_ID NUMERIC (22),
PRODUCT_ID NUMERIC (22),
QUANTITY NUMERIC (22),
UNIT_PRICE NUMERIC (22))


create table NORTHWIND.ORDERS(
EMPLOYEE_ID NUMERIC (22),
FREIGHT NUMERIC (22),
ORDER_DATE DATE,
ORDER_ID NUMERIC (22),
REQUIRED_DATE DATE,
SHIP_ADDRESS VARCHAR (60),
SHIP_CITY VARCHAR (15),
SHIP_COUNTRY VARCHAR (15),
SHIP_NAME VARCHAR (40),
SHIPPED_DATE DATE,
SHIP_POSTAL_CODE VARCHAR (10),
SHIP_REGION VARCHAR (15),
SHIP_VIA NUMERIC (22))

create table NORTHWIND.PRODUCTS(
DISCONTINUED CHAR (1),
PRODUCT_ID NUMERIC (22),
PRODUCT_NAME VARCHAR (40),
QUANTITY_PER_UNIT VARCHAR (20),
REORDER_LEVEL NUMERIC (22),
SUPPLIER_ID NUMERIC (22),
UNIT_PRICE NUMERIC (22),
UNITS_IN_STOCK NUMERIC (22),
UNITS_ON_ORDER NUMERIC (22))

create table NORTHWIND.SHIPPERS(
PHONE VARCHAR (24),
SHIPPER_ID NUMERIC (22))

create table NORTHWIND.SUPPLIERS(
CITY VARCHAR (15),
COMPANY_NAME VARCHAR (40),
CONTACT_NAME VARCHAR (30),
CONTACT_TITLE VARCHAR (30),
COUNTRY VARCHAR (15),
FAX VARCHAR (24),
HOME_PAGE VARCHAR (500),
PHONE VARCHAR (24),
POSTAL_CODE VARCHAR (10),
REGION VARCHAR (15),
SUPPLIER_ID NUMERIC (22))


select * from customers 

create table DIM_CLIENTE 
(ID_CUSTOMER INT IDENTITY CONSTRAINT PK_CLIENTE PRIMARY KEY,
BK_CUSTOMER VARCHAR(20),
CITY VARCHAR(30),
COUNTRY VARCHAR(30),
CUSTOMER_NAME VARCHAR(30),
CONTACT_NAME VARCHAR(80),
)

DIM_PRODUCTO
DIM_EMPLEADO

DIM_TIEMPO

